### ISSUE TITLE
x-select.js:151 Uncaught TypeError: Cannot read property 'is' of undefined

### ISSUE THREAD

**Issue by arthur-s** [thefrontside/emberx-select#144]
### Ember Version / Ember CLI Version:

**Ember Version: 2.7.2**
**Ember CLI Version:**
### Expected Behavior

In my template i have:

``` hbs
{{#x-select value=(mut (get modelRelationsValues key)) class="chosen-select" as |xs|}}
    {{#xs.option value=''}}{{/xs.option}}
    {{#each choices as |option|}}
        {{#xs.option value=(get (json2obj option.value) 'id')}} {{option.display_name}} {{/xs.option}}
    {{/each}}
{{/x-select}}
```
### Actual Behavior

On select any item throws this error (Cannot read property 'is' of undefined)
### Ember Twiddle / Example repo / Failing test:

_Please create a reproduction of your [bug with this ember-twiddle](https://ember-twiddle.com/278fcd6b13e8b9a06d09e7023f178496). This is extremely helpful and speeds up the debugging process._

**Comment by Robdel12** [comment]
Hi @arthur-s! Is there anyway you can make an ember twiddle for this? I tried plugging in what you have in your template and I can't reproduce. I'm going to guess something is going on with the value of `json2obj` being null or undefined

**Comment by fivetanley** [comment]
~~might~~ be related https://github.com/thefrontside/emberx-select/pull/148

**Comment by arthur-s** [comment]
@Robdel12, I cannot recreate my situation on Twiddle, becouse when i select latest Ember.js or Ember Data, in the debug console i always see
```
DEBUG: Ember      : 2.5.1
VM135 ember.debug.js:6440 DEBUG: Ember Data : 2.5.2
VM135 ember.debug.js:6440 DEBUG: jQuery     : 1.11.3
```
Not the latest version.

**Comment by arthur-s** [comment]
Now i tried to use x-select (installed from git repository, dev version), and this error occured when I navigated to page, containing select box:
```
x-option.js:77 Uncaught TypeError: _this.get(...) is not a function
```

**Comment by Robdel12** [comment]
@arthur-s current master is basically x-select 3.0, so there's a lot of breaking changes there. Could you push an example repo and I can take a look at that?

**Comment by thagul** [comment]
I've received the same error, I'm trying to reproduce it but unsuccessfully until now.
My template is

```
{{#x-select value=model.country as |xs|}}
  {{#each countryList as |country|}}
    {{#xs.option value=country.id}}
      {{ country.country }}
    {{/xs.option}}
  {{/each}}
{{/x-select}}
```

I'm pretty sure that `model.country` was `null`, `countryList` is an array of ember objects containing ~250 elements like this:

```
{ id: "US", country: "USA" }
```

I've received ~250 error notifications, one for each option in the select but only for one user. Other users were able to use the select without problems.

Currently I'm using:
emberx-select: 2.2.2
ember-data: ^2.8.0
ember.js: ~2.8.0

**Comment by Robdel12** [comment]
I think this has been fixed in v2.2.3. I'll reopen if that's not the case.

**Comment by newton3** [comment]
I am running `"emberx-select": "^3.0.0",` but still have this error. What was the fix when using this?

`ember.debug.js:18008 TypeError: _this.get(...) is not a function
    at x-option.js:75
    at invokeWithOnError (ember.debug.js:346)
    at Queue.flush (ember.debug.js:405)
    at DeferredActionQueues.flush (ember.debug.js:529)
    at Backburner.end (ember.debug.js:599)
    at Backburner.run (ember.debug.js:713)
    at Backburner.join (ember.debug.js:744)
    at Function.run.join (ember.debug.js:22732)
    at Object.hash.success (ajax-request.js:231)
    at fire (jquery.js:3317)
defaultDispatch	@	ember.debug.js:18008
dispatchError	@	ember.debug.js:17987
invokeWithOnError	@	ember.debug.js:349
flush	@	ember.debug.js:405
flush	@	ember.debug.js:529
end	@	ember.debug.js:599
run	@	ember.debug.js:713
join	@	ember.debug.js:744
run.join	@	ember.debug.js:22732
hash.success	@	ajax-request.js:231
fire	@	jquery.js:3317
fireWith	@	jquery.js:3447
done	@	jquery.js:9272
(anonymous)	@	jquery.js:9514
(anonymous)	@	fake_xml_http_request.js:137
dispatchEvent	@	fake_xml_http_request.js:181
_readyStateChange	@	fake_xml_http_request.js:381
_setResponseBody	@	fake_xml_http_request.js:445
respond	@	fake_xml_http_request.js:466
(anonymous)	@	pretender.js:369
resolve	@	pretender.js:418
(anonymous)	@	pretender.js:409`

**Comment by Robdel12** [comment]
Hey @newton3, if you're using x-select 3.0 you should be using contextual components. If you update your HBS to this does it still throw the same error?

```hbs            
{{#x-select action='selectAppType' id="app-type-select" value=model.AppType class="form-control" as |xs|}}
  {{#each model.AppTypes as |appType|}} {{log appType}}
    {{#xs.option value=appType}}
      {{appType}}
    {{/xs.option}}
  {{/each}}
{{/x-select}}
```

**Comment by newton3** [comment]
Thanks @Robdel12 , this seems to solve the issue but can you please explain what |xs| does or point me documentation for the same? It seems to have magically fixed the issue :-).

**Comment by Robdel12** [comment]
Absolutely! Think of it as a component "wrapping" a component. `x-option` will always be used as a child of `x-select`. Since that will always be true we can do things like automatically pass the [instance of `x-select` down to `x-option`. We also register `x-option` with x-select. ](https://github.com/thefrontside/emberx-select/blob/master/addon/templates/current/components/x-select.hbs#L3)

 Here's a couple links: 
- https://emberjs.com/blog/2015/11/16/ember-2-2-released.html#toc_contextual-components
- https://guides.emberjs.com/v2.5.0/components/wrapping-content-in-a-component/
